### ISSUE TITLE
VS Enterprise is Missing from Final Image

### ISSUE THREAD

**Issue by digitalbydesign** [KrylixZA/Azure-Pipelines-Docker-Agents#4]
**Describe the bug**
After a successful build/run of the container the final image doesn't appear to have Visual Studio 2019/2022 installed. All chocolatey installs are there but not visual studio.

**Expected behavior**
Visual Studio 2019/2022 should be installed upon container start.

**Additional context**
I'm wondering if this could be a space issue with the windows container. Just curious if you have anything special set to get this to install properly.

**Comment by KrylixZA** [comment]
Hey @digitalbydesign - thanks for raising the issue.

It almost certainly is an issue related to the space. It appears that when building the Docker image, the memory limitations of the various layers limits what workflows can and can't be installed. I am actually looking to deprecate the existing Docker Hub repository and replace it with a newer one with multiple variations available.

In the mean time, to get you unstuck, I've been using the [1.0.1.36](https://github.com/KrylixZA/Azure-Pipelines-Docker-Agents/releases/tag/1.0.1.36) release and it's been working okay for me so give that a go for now. I will let you know when this issue is resolved 😃

**Comment by digitalbydesign** [comment]
Thanks for the prompt reply. I've been trying for days now to get a windows docker build agent working and my biggest hurdle has been SSDT for building sqlproj files. I'm hoping this works for our use case.

**Comment by KrylixZA** [comment]
Should do as we build use these images to build DACPAC projects!

I am busy working on more options and granular control variants now but for now 1.0.1.36 should do 👍

**Comment by digitalbydesign** [comment]
Quick question, are you running these build containers on Azure Container Instances? Just curious if a 44GB image will be able to pull/start in their 30 minute window. Thanks!

**Comment by KrylixZA** [comment]
No I am running on-prem. 

If you need, I have created the following images which may be better suited for you: [krylixza/azure-pipelines-windows-build-agent](https://hub.docker.com/repository/docker/krylixza/azure-pipelines-windows-build-agent)

| Image | Description | Compressed Size |
|----|----|----|
|  `2019-enterprise-x.x.x.x` | Visual Studio 2019 Enterprise workloads. | ~11GB |
|  `2022-enterprise-x.x.x.x` | Visual Studio 2022 Enterprise workloads. | ~12GB |
|  `2019-buildtools-x.x.x.x` | Visual Studio 2019 Build Tools workloads. | ~7GB |
|  `2022-buildtools-x.x.x.x` | Visual Studio 2022 Build Tools workloads. | ~8GB |

Digging in to your specific situation, needing to build SQL project files, you could get away with any of the options and possibly the best solution would be the `2019-buildtools-x.x.x.x` version.

I have yet to merge these new Docker images into the main branch here you could try using the following pre-release build: [2019-buildtools-1.0.1.45-mutli-workflows](https://hub.docker.com/layers/krylixza/azure-pipelines-windows-build-agent/2019-buildtools-1.0.1.45-mutli-workflows/images/sha256-2e0b513847fd18cf5313fa84a700d40fd574844c32814ada7b3c4ce8fc55af0d?context=repo)

**Comment by KrylixZA** [comment]
@digitalbydesign have you had any luck trying out either the `2019-buildtools` or `2022-buildtools` images? 

I have run tests my side with the Enterprise images and they appear to be working as expected. I will hopefully get time later tonight to resolve the comments on my #5 PR and get `main` branch builds going.

**Comment by digitalbydesign** [comment]
I've tried both the 2019 & 2022 Enterprise images and both of those have worked for our use case. I'm going to try the 2019 build tools image to see if it's small enough to properly start on ACI. I'd really love to see your dockerfile for the 2019/2022 build tools images. I had been working on my own images for quite some time but could never get the SSDT stuff to install right for sqlproj builds. Thanks again for the assist!

**Comment by KrylixZA** [comment]
Awesome stuff! Glad to hear you came right! 🥇 

Here is the Dockerfile: https://github.com/KrylixZA/Azure-Pipelines-Docker-Agents/blob/c1357557d4b4660c57fba8360be588af9e3a7be5/src/build-agent/windows/vs/buildTools/2019/Dockerfile
You could potentially trim some space out of the Docker image if you have no need to run UI tests and other workflows outside of building SSDT projects by taking just the following code as your Dockerfile:

```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

SHELL ["cmd", "/S", "/C"]

WORKDIR /TEMP
 
# Add installers
ADD https://aka.ms/vs/16/release/vs_buildtools.exe vs_buildtools.exe

# Visual Studio 2019 Build Tools
RUN .\vs_buildtools.exe \
    --quiet \
    --wait \
    --norestart \
    --nocache \
    --add Microsoft.VisualStudio.Workload.AzureBuildTools \
    --add Microsoft.VisualStudio.Workload.DataBuildTools \
    --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools \
    --add Microsoft.VisualStudio.Workload.MSBuildTools \
    --add Microsoft.VisualStudio.Workload.NetCoreBuildTools \
    --includeRecommended \
    --includeOptional \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0;

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

WORKDIR /

# Cleanup after installs
RUN Remove-Item C:\TEMP -Recurse;
 
# Copy & run Azure Pipelines Agent startup script
COPY start.ps1 .
ENTRYPOINT .\start.ps1
```

I think possibly you were missing the following workloads during your install:
`--add Microsoft.VisualStudio.Workload.DataBuildTools`

You can read more about workloads and component identifiers here: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#data-storage-and-processing-build-tools

---
As a side note, the build tools should be just fine. I had the 2019 build tools running for the majority of last year without problems. Some teams running older .NET Framework 4.5 and 4.6 projects that needed the runtime and targeting packs to launch their APIs in the CI pipeline migrated to Azure DevOps and that drew me to the Enterprise solution instead as it comes with that out of the gate. 
So for your purposes, the build tools should suffice 👍

**Comment by digitalbydesign** [comment]
That's the thing, I was adding the mentioned workload above but my build pipeline kept complaining about SqlTasks.targets file and searching for missing assemblies. I'm pushing the stripped down image to ACR now to see if my CI will properly start. Funny thing about ACI, even with large images the container(s) inside the instance do eventually start but since it takes longer than the 30 minute timeout the instance itself gets marked as failed and won't allow you to exec into the container. Not good for production workloads. Many thanks again for the assist!

**Comment by KrylixZA** [comment]
Happy days!

**Comment by KrylixZA** [comment]
Closing this issue as #5 was merged last night 👍
